---
title: ""
format: html
editor: visual
bibliography: references.bib
csl: clinical-infectious-diseases.csl
---

# The Pharmacological Basis of Mucormycosis Therapy

Russell E. Lewis, Pharm.D.^1^

^1^Associate Professor, Infectious Diseases Department of Molecular Medicine, University of Padua , Padua, Italy

## Introduction

Mucormycosis encompasses a spectrum of diseases caused by fungi in the order Mucorales that have a predisposition for causing aggressive, life-threatening pneumonia or rhino-orbital- cerebral infection in the severely immunocompromised, transplant or diabetic patients. Survival from these infections often depends on reversal of underlying predisposing metabolic or immunosuppressive conditions, surgical resection of infected tissue, and the timely administration of effective antifungal therapy. [@Chamilos2008503; @jeong2015]. Unfortunately, limited diagnostic tools and effective treatment options contributes to the high mortality associated with invasive mucormycosis. These challenges recently prompted the World Health Organization (WHO) to classify invasive mucormycosis as a fungal pathogen of "High Priority" for further research and development needs.

Amphotericin B is the long-standing drug of choice for mucormycosis [@cornely_etal19a]with most clinicians favouring administration of the less-nephrotoxic liposomal amphotericin B formulation at higher-doses (5-10 mg/kg/day) to rapidly load target tissues such as the lung and brain with amphotericin B to slow fungal tissue invasion and dissemination into these [@groll_etal19]. Patients with lack of clinical response or intolerance to amphotericin B may be switched to posaconazole or isavuconazole, or transitioned to oral formulations of these triazoles once infection has stabilized to complete therapy[@kontoyiannis_lewis11; @cornely_etal19a]. Yet, the treatment of mucormycosis is still limited by the lack of effective treatment alternatives who cannot tolerate front-line therapies because of toxicities, drug interactions, or are infected with multidrug-resistant strains \[ \]

In the previous monograph published from the First International Henry Schueler Supplement on Mucormycosis [@lewis_etal12], we examined how antifungal pharmacology and resistance differs for Mucorales versus more common *Aspergillus* infections. Since the publication of this monograph, new data has been published on Mucorales species-specific susceptibility profiles, triazole pharmacokinetic/pharmacodynamics (PK/PD), and the antifungal pipeline has grown (?) with several possible new therapeutic classes that may have a role for refractory infections. In this monograph, we will review the pharmacological basis for antifungal therapy in mucormycosis with a particular focus on new data published in the last 5-10 years that may shape future treatment strategies for this devastating infection.

## Pharmacodynamic challenges

### In vitro susceptibility

Table 1. In vitro susceptibility profiles for common Mucorales spp.

| Species           | Amphotericin B | Itraconazole | Posaconazole | Isavuconazole |
|---------------|---------------|---------------|---------------|---------------|
| L. corymbifera    |                |              |              |               |
| M. cicinellloides |                |              |              |               |
| R. arhizus        |                |              |              |               |
| R. microsporus    |                |              |              |               |
| M.                |                |              |              |               |

#### 

Breakpoints versus ECVs - Can we assume amphotericin B susceptibility ? - Espinel-Ingroff A, Chakrabarti A, Chowdhary A, Cordoba S, Dannaoui E, Dufresne P, et al. Multicenter evaluation of MIC distributions for epidemiologic cutoff value definition to detect amphotericin B, posaconazole, and itraconazole resistance among the most clinically relevant species of Mucorales. Antimicrobial agents and chemotherapy \[Internet\]. 2015 Mar;59(3):1745--50. Available from: http://dx.doi.org/10.1128/AAC.04435-14 - Do MICs predict outcome? - Lamoth F, Damonti L, Alexander BD. Role of Antifungal Susceptibility Testing in Non-Aspergillus Invasive Mold Infections. Journal of clinical microbiology \[Internet\]. 2016 Jun;54(6):1638--40. Available from: http://dx.doi.org/10.1128/JCM.00318-16 - Species-specific susceptibility-especially important for triazoles? - Wagner L, de Hoog S, Alastruey-Izquierdo A, Voigt K, Kurzai O, Walther G. A Revised Species Concept for Opportunistic Mucor Species Reveals Species-Specific Antifungal Susceptibility Profiles. Antimicrobial agents and chemotherapy \[Internet\]. 2019 Aug;63(8). Available from: http://dx.doi.org/10.1128/AAC.00653-19 - Media effects on Rhizopus virulence \## Pharmacokinetic challenges \## Treatment window-angioinvasion and tissue necrosis - Consider new figure - Old versus new: homogized tissue versus MALDI-MSI imaging - Penetration of drug into anatomically-privlidges sites - Intracellular antifungal activity insice macrophages and granulomas \## Integrating PK/PD concepts \### The Complex pharmacokinetics of liposomal AMB - feasibility of dose escalation to improve outcomes \### Triazole antifungals - Feasibility of dosage escalation to improve outcomes \### New hope from the antifungal pipeline? - In vitro vs. in vivo correlation - Combination therapy \## Summary - maturation of antifungal susceptibility testing - limited PK/PD basis for current antifungal dosing - The dire need for clinically-reliable biomarkers - Current limitations of antifungals in terms of complecx PK, toxicity, drug interactions - No phamracometrics/dosign guidance

## References
